POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Tiitiaisen satupuu",
    "author": "Teppo Tiitiainen",
    "url": "http://wwww.example.com",
    "likes": 5,
    "userId": "68d166e868564064454b759e"
}